name: Integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  trigger-feature-branch:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - name: Clean repo
        run: |
          cd ..
          rm -rf .west
          ls -a

      - name: Initialize
        run: |    
          west init -l .
          west update -o=--depth=1 -n

      - name: Clean up previous output
        run: |
          rm -rf twister-out*

      - name: Run and build dut
        run: |
          dut_path="tests/integration/dut/"
          
          cd $dut_path
          rm -rf build
          west build -b nrf52dk_nrf52832 . \
            && west flash -r openocd --cmd-pre-init 'adapter serial 1050376244'

      - name: Run and build testrunner
        run: |
          output_file="./test_output.txt" 
          tests_path="tests/integration/tester"

          cd $tests_path
          west twister --device-testing --hardware-map map.yml \
            -T . > $output_file

      - name: Upload Test Logs as Coverage Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: integration-testreport
          path: |
            ./tests/integration/tester/test_output.txt
            ./tests/integration/tester/twister-out/nrf52dk_nrf52832/integration.test_case/handler.log
            ./tests/integration/tester/twister-out/nrf52dk_nrf52832/integration.test_case/integration.test_case/build.log
            
      - name: Clean repo
        run: |
          cd ..
          rm -rf .west
          ls -a
